export const copy = {
  en: {
    hero: "The AI-powered TMS ecosystem for transport companies.",
    pillars: "Operations. Fleet. Finance. Data. Intelligence.",
    intro:
      "Bring your entire transport operation into one connected ecosystem — from the first transport order to invoicing, analytics, and decision-making.",
    cta: "Take ATLASZ for a test drive",
    scroll: "Scroll to follow the journey",
    demo: "Interactive preview · Example data",
    chapters: [
      "The ecosystem",
      "Capture data",
      "Organize operations",
      "Costs & spot pricing",
      "Track your fleet",
      "Driver app",
      "Intelligence & migration",
      "Back at the depot",
    ],
    capture: [
      "Everything from cargo to invoicing",
      "Automatically capture data from transport orders, bills, receipts, documents, and photos.",
    ],
    operations: [
      "Keep your operation moving.",
      "Transports, routes, vehicles, drivers, partners, and assignments. Together in one place.",
    ],
    finance: [
      "Know the cost. Price the transport.",
      "Estimate route costs, see your margin, and build a spot quote before you commit.",
    ],
    tracking: [
      "Your fleet. Connected.",
      "ATLASZ brings GPS location and FMS vehicle data together, connecting what happens on the road with your transport operation.",
    ],
    telemetry: [
      ["GPS · Location and movement", "See where your vehicles are and follow their journeys."],
      ["FMS · Vehicle operating data", "Bring fuel use, mileage, and other vehicle readings into one view."],
    ],
    devices: ["Planned · ATLASZ devices", "In the future, our own devices installed in your trucks will collect vehicle data directly."],
    mobile: [
      "Your operation doesn’t stop at the office. Neither does ATLASZ.",
      "ATLASZ for iOS and Android connects drivers with the office — unlock fueling, exchange messages, and collect documents and photos from the road.",
    ],
    intelligence: [
      "See what comes next.",
      "Use ATLASZ AI to discover trends, forecast demand, and find opportunities to buy and sell transport orders.",
    ],
    migration: [
      "Bring your existing operation with you.",
      "Import your data. Connect existing systems and automate workflows with Atlasz Bot. Get started with onboarding, training, and ongoing support.",
    ],
    invoice: [
      "Delivered. Ready to invoice.",
      "Turn completed transports into invoices without entering the same information twice.",
    ],
    service: [
      "Ready for the next trip.",
      "Plan vehicle servicing and manage spare parts and inventory, together with your fleet.",
    ],
    partners: "Built alongside transport companies.",
    closing: "Your next journey starts here.",
    assigned: "Assigned",
    vehicle: "Vehicle",
    driver: "Driver",
    cargo: "Cargo",
    pallets: "12 pallets · Refrigerated",
    delivery: "Delivery",
    live: "Fleet connected",
    fuel: "Fuel",
    tolls: "Tolls",
    driverCost: "Driver",
    other: "Other",
    total: "Estimated cost",
    margin: "Target margin",
    quote: "Spot quote",
    profit: "Estimated profit",
    unlock: "Unlock fueling",
    unlocked: "Fueling unlocked",
    ready: "You can start fueling at pump 04.",
    authorize: "Authorize pump 04 for your assigned vehicle.",
    reset: "Try again",
    app: "Driver app",
    station: "Fuel stop · Pump 04",
    secure: "Vehicle verified",
    forecast: "Margin forecast",
    forecastValue: "+4.2 pts",
    insight:
      "Fuel costs are trending down. At the current rate, next week’s route margins could improve.",
    insightNote: "Illustrative forecast based on example data.",
    bot: "Atlasz Bot",
    botSteps: [
      "Connect your existing systems",
      "Bring your data together",
      "Automate everyday workflows",
    ],
    invoiceLabel: "Invoice draft",
    invoiceStatus: "Ready for review",
    serviceLabel: "Next service",
    serviceValue: "Oil & filter change",
    stock: "Parts in stock",
    stockValue: "8 oil filters",
    reserved: "1 reserved for this vehicle",
    complete: "Transport completed",
  },
  hu: {
    hero: "AI-alapú TMS ökoszisztéma fuvarozó vállalatoknak.",
    pillars: "Operáció. Flotta. Pénzügy. Adatok. Intelligencia.",
    intro:
      "A teljes fuvarozási működés egy összekapcsolt ökoszisztémában — az első megbízástól a számlázáson át az elemzésig és a döntéshozatalig.",
    cta: "Próbálja ki az ATLASZ-t",
    scroll: "Görgessen végig az úton",
    demo: "Interaktív bemutató · Példaadatok",
    chapters: [
      "Ökoszisztéma",
      "Adatgyűjtés",
      "Fuvarszervezés",
      "Költségek és spot árak",
      "Flottakövetés",
      "Sofőrapplikáció",
      "AI és migráció",
      "Vissza a telephelyre",
    ],
    capture: [
      "A rakománytól a számlázásig",
      "Automatikus adatkinyerés megbízásokból, számlákból, nyugtákból, dokumentumokból és fotókból.",
    ],
    operations: [
      "Tartsa mozgásban a vállalkozását.",
      "Fuvarok, útvonalak, járművek, sofőrök, partnerek és feladatok egy helyen.",
    ],
    finance: [
      "Ismerje a költséget. Árazza a fuvart.",
      "Becsülje meg az útvonal költségeit, lássa az árrést, és készítsen spot árajánlatot a vállalás előtt.",
    ],
    tracking: [
      "Kapcsolatban a flottával.",
      "Az ATLASZ összegyűjti a GPS-helyadatokat és az FMS járműadatokat, így az úton történő események a fuvarszervezésben is követhetők.",
    ],
    telemetry: [
      ["GPS · Helyzet és mozgás", "Lássa, hol járnak a járművei, és kövesse az útjukat."],
      ["FMS · Járműüzemi adatok", "Üzemanyag-fogyasztás, futásteljesítmény és további járműadatok egy helyen."],
    ],
    devices: ["Tervezett · ATLASZ eszközök", "Később a teherautókba telepített saját eszközeink közvetlenül gyűjtik majd a járműadatokat."],
    mobile: [
      "A munka nem áll meg az irodánál. Az ATLASZ sem.",
      "Az ATLASZ iOS és Android alkalmazása összeköti a sofőröket az irodával: tankolás engedélyezése, üzenetváltás, dokumentumok és fotók közvetlenül az útról.",
    ],
    intelligence: [
      "Lássa, mi következik.",
      "Fedezze fel a trendeket, jelezze előre a keresletet, és találjon lehetőségeket fuvarmegbízások vásárlására és eladására az ATLASZ AI segítségével.",
    ],
    migration: [
      "Hozza magával a meglévő működését.",
      "Importálja adatait. Az Atlasz Bot összekapcsolja meglévő rendszereit és automatizálja a munkafolyamatokat. Bevezetés, képzés és folyamatos támogatás.",
    ],
    invoice: [
      "Kiszállítva. Számlázásra kész.",
      "Készítsen számlát a teljesített fuvarból az adatok ismételt rögzítése nélkül.",
    ],
    service: [
      "Készen a következő útra.",
      "Tervezze meg a szervizelést, és kezelje az alkatrészeket és készleteket a flottával együtt.",
    ],
    partners: "Fuvarozó vállalatokkal közösen építjük.",
    closing: "Itt kezdődik a következő útja.",
    assigned: "Kiosztva",
    vehicle: "Jármű",
    driver: "Sofőr",
    cargo: "Rakomány",
    pallets: "12 raklap · Hűtött",
    delivery: "Kiszállítás",
    live: "Flotta csatlakoztatva",
    fuel: "Üzemanyag",
    tolls: "Útdíj",
    driverCost: "Sofőr",
    other: "Egyéb",
    total: "Becsült költség",
    margin: "Célárrés",
    quote: "Spot árajánlat",
    profit: "Becsült nyereség",
    unlock: "Tankolás engedélyezése",
    unlocked: "Tankolás engedélyezve",
    ready: "Megkezdheti a tankolást a 04-es kútnál.",
    authorize: "Engedélyezze a 04-es kutat a hozzárendelt járműhöz.",
    reset: "Újra",
    app: "Sofőrapplikáció",
    station: "Tankolás · 04-es kút",
    secure: "Jármű ellenőrizve",
    forecast: "Árrés-előrejelzés",
    forecastValue: "+4,2 pont",
    insight:
      "Az üzemanyagköltségek csökkennek. A jelenlegi trend alapján a jövő heti fuvarok árrése javulhat.",
    insightNote: "Szemléltető előrejelzés példaadatok alapján.",
    bot: "Atlasz Bot",
    botSteps: [
      "Meglévő rendszerek összekapcsolása",
      "Adatok egy helyen",
      "Mindennapi munkafolyamatok automatizálása",
    ],
    invoiceLabel: "Számlatervezet",
    invoiceStatus: "Ellenőrzésre vár",
    serviceLabel: "Következő szerviz",
    serviceValue: "Olaj- és szűrőcsere",
    stock: "Raktáron",
    stockValue: "8 olajszűrő",
    reserved: "1 lefoglalva ehhez a járműhöz",
    complete: "Fuvar teljesítve",
  },
};
export type LandingCopy = typeof copy.en;
